import {
  useMutation,
  useQuery,
  useQueryClient,
  type QueryClient,
} from '@tanstack/react-query';
import { supabase } from './supabase';
import { CardPayload, DeckInput, Grade, ProfileSettings, type CardKind } from './schemas';
import { applyGrade, newCardScheduling, type SchedulePreview } from './fsrs';
import { resolveTimeZone, startOfStudyDay } from './day';
import { buildQueue, remainingNewAllowance } from './queue';
import type { Database } from '@/types/database';

/**
 * Every read and write the app performs, as TanStack Query hooks over
 * supabase-js. Thin on purpose: policy lives in fsrs.ts and queue.ts, atomicity
 * lives in the `review_card` RPC, and this file is the wiring between them.
 *
 * Two rules hold throughout:
 *   - Validate with the shared Zod schemas *before* the network call, so bad
 *     data fails locally with a field-level message instead of as a 400.
 *   - Never send `user_id` from a form. It comes from the session, and RLS
 *     rejects anything else anyway (SPEC §5.7).
 */

export type CardRow = Database['public']['Tables']['cards']['Row'];
export type DeckRow = Database['public']['Tables']['decks']['Row'];
export type ProfileRow = Database['public']['Tables']['profiles']['Row'];

/** Query keys, as SPEC §8.3. Deck-scoped data nests under `['deck', id]` so one
 *  invalidation covers the deck and its cards. */
export const queryKeys = {
  decks: ['decks'] as const,
  deck: (deckId: string) => ['deck', deckId] as const,
  deckCards: (deckId: string) => ['deck', deckId, 'cards'] as const,
  queue: (deckId?: string) => ['queue', deckId ?? 'all'] as const,
  profile: ['profile'] as const,
};

/**
 * Error codes raised by supabase/migrations/20260812093000_review_card.sql.
 * A stale rating is an expected outcome, not a crash: it means the card was
 * already rated somewhere else.
 */
export const RPC_ERROR = {
  staleCard: 'PT409',
  notFound: 'PT404',
} as const;

export function isStaleCardError(error: unknown): boolean {
  return (error as { code?: string } | null)?.code === RPC_ERROR.staleCard;
}

/**
 * How many due cards one queue fetch pulls. A session is not a spreadsheet;
 * beyond a few hundred cards the number stops being actionable, and the next
 * fetch picks up whatever is left. Reviews are never *dropped* by this — they
 * are still due, and still first in line.
 */
export const QUEUE_FETCH_LIMIT = 400;

/**
 * Cards are selected whole. Every column except `user_id` is used somewhere —
 * content to render, scheduling to grade against, `updated_at` as the
 * concurrency token — and a hand-maintained column list is one more place to
 * forget a migration. supabase-js also infers row types only from a literal
 * selector, so `'*'` is what keeps `CardRow` honest.
 */
const CARD_COLUMNS = '*';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

type PostgrestResult<T> = { data: T | null; error: { message: string } | null };

/** Throw supabase-js errors so TanStack Query sees a rejected promise. */
function unwrap<T>(result: PostgrestResult<T>): T {
  if (result.error) throw result.error;
  if (result.data === null) throw new Error('The server returned no row.');
  return result.data;
}

/** Same, for reads where "no row" is a legitimate answer. */
function unwrapMaybe<T>(result: PostgrestResult<T>): T | null {
  if (result.error) throw result.error;
  return result.data;
}

/** The signed-in user's id. Mutations need it; RLS will not accept any other. */
async function currentUserId(): Promise<string> {
  const { data, error } = await supabase.auth.getSession();
  if (error) throw error;
  const userId = data.session?.user.id;
  if (!userId) throw new Error('You are signed out. Sign in and try again.');
  return userId;
}

/**
 * A card's content, validated.
 *
 * Card payloads are untrusted (§10): generated by an LLM in P2, and stored as
 * free-form jsonb. Anything that fails the schema is surfaced as a broken card
 * the user can edit or delete, never rendered on a guess.
 */
export function parseCardPayload(row: Pick<CardRow, 'payload'>): CardPayload | null {
  const parsed = CardPayload.safeParse(row.payload);
  return parsed.success ? parsed.data : null;
}

// ---------------------------------------------------------------------------
// Profile
// ---------------------------------------------------------------------------

export function useProfile() {
  return useQuery({
    queryKey: queryKeys.profile,
    queryFn: async (): Promise<ProfileRow | null> => {
      const userId = await currentUserId();
      const result = await supabase
        .from('profiles')
        .select('*')
        .eq('id', userId)
        .maybeSingle();
      return unwrapMaybe(result);
    },
    // The timezone here decides every day boundary; a stale copy shifts the
    // new-card cap. Cheap row, so just keep it fresh.
    staleTime: 60_000,
  });
}

export function useUpdateProfile() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (input: ProfileSettings) => {
      const settings = ProfileSettings.parse(input);
      const userId = await currentUserId();
      const result = await supabase
        .from('profiles')
        .update({
          display_name: settings.display_name?.trim() || null,
          timezone: settings.timezone,
          daily_new_limit: settings.daily_new_limit,
        })
        .eq('id', userId)
        .select()
        .single();
      return unwrap(result);
    },
    onSuccess: profile => {
      queryClient.setQueryData(queryKeys.profile, profile);
      // The day boundary and the cap both moved; every queue is now suspect.
      void queryClient.invalidateQueries({ queryKey: ['queue'] });
    },
  });
}

// ---------------------------------------------------------------------------
// Decks
// ---------------------------------------------------------------------------

export type DeckWithCounts = DeckRow & {
  cardCount: number;
  dueCount: number;
  newCount: number;
};

/**
 * Decks with their card, due and new counts.
 *
 * The counts come from one card fetch rather than three aggregate round trips:
 * `select deck_id, status, fsrs_state, due` over a user's own cards is small and
 * index-covered, and it keeps the deck list a single request.
 */
export function useDecks() {
  return useQuery({
    queryKey: queryKeys.decks,
    queryFn: async (): Promise<DeckWithCounts[]> => {
      const decks = unwrap(
        await supabase
          .from('decks')
          .select('*')
          .neq('status', 'failed')
          .order('updated_at', { ascending: false }),
      );

      const counters = unwrap(
        await supabase
          .from('cards')
          .select('deck_id, fsrs_state, due')
          .eq('status', 'active'),
      );

      const now = Date.now();
      const byDeck = new Map<string, { cards: number; due: number; fresh: number }>();
      for (const card of counters) {
        const bucket = byDeck.get(card.deck_id) ?? { cards: 0, due: 0, fresh: 0 };
        bucket.cards += 1;
        if (card.fsrs_state === 'new') bucket.fresh += 1;
        else if (new Date(card.due).getTime() <= now) bucket.due += 1;
        byDeck.set(card.deck_id, bucket);
      }

      return decks.map(deck => {
        const bucket = byDeck.get(deck.id);
        return {
          ...deck,
          cardCount: bucket?.cards ?? 0,
          dueCount: bucket?.due ?? 0,
          newCount: bucket?.fresh ?? 0,
        };
      });
    },
  });
}

export function useDeck(deckId: string | undefined) {
  return useQuery({
    queryKey: queryKeys.deck(deckId ?? ''),
    enabled: Boolean(deckId),
    queryFn: async (): Promise<DeckRow> => {
      const result = await supabase.from('decks').select('*').eq('id', deckId!).single();
      return unwrap(result);
    },
  });
}

export function useCreateDeck() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (input: DeckInput) => {
      const deck = DeckInput.parse(input);
      const userId = await currentUserId();
      const result = await supabase
        .from('decks')
        .insert({
          user_id: userId,
          title: deck.title,
          description: deck.description || null,
          source: 'manual',
          status: 'active',
        })
        .select()
        .single();
      return unwrap(result);
    },
    onSuccess: () => queryClient.invalidateQueries({ queryKey: queryKeys.decks }),
  });
}

export function useUpdateDeck() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async ({ deckId, ...input }: DeckInput & { deckId: string }) => {
      const deck = DeckInput.parse(input);
      const result = await supabase
        .from('decks')
        .update({ title: deck.title, description: deck.description || null })
        .eq('id', deckId)
        .select()
        .single();
      return unwrap(result);
    },
    onSuccess: deck => {
      queryClient.setQueryData(queryKeys.deck(deck.id), deck);
      void queryClient.invalidateQueries({ queryKey: queryKeys.decks });
    },
  });
}

export function useDeleteDeck() {
  const queryClient = useQueryClient();
  return useMutation({
    // Cards cascade with the deck (§5.3 references ... on delete cascade), so
    // this is genuinely destructive — the caller must confirm first (§10).
    mutationFn: async (deckId: string) => {
      unwrap(await supabase.from('decks').delete().eq('id', deckId).select('id'));
      return deckId;
    },
    onSuccess: deckId => {
      queryClient.removeQueries({ queryKey: queryKeys.deck(deckId) });
      void queryClient.invalidateQueries({ queryKey: queryKeys.decks });
      void queryClient.invalidateQueries({ queryKey: ['queue'] });
    },
  });
}

// ---------------------------------------------------------------------------
// Cards
// ---------------------------------------------------------------------------

export function useCards(deckId: string | undefined) {
  return useQuery({
    queryKey: queryKeys.deckCards(deckId ?? ''),
    enabled: Boolean(deckId),
    queryFn: async (): Promise<CardRow[]> => {
      const result = await supabase
        .from('cards')
        .select(CARD_COLUMNS)
        .eq('deck_id', deckId!)
        .neq('status', 'archived')
        .order('created_at', { ascending: true });
      return unwrap(result);
    },
  });
}

export type CreateCardInput = {
  deckId: string;
  payload: CardPayload;
  sourceExcerpt?: string | null;
};

export function useCreateCard() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async ({ deckId, payload, sourceExcerpt }: CreateCardInput) => {
      const content = CardPayload.parse(payload);
      const userId = await currentUserId();
      const result = await supabase
        .from('cards')
        .insert({
          user_id: userId,
          deck_id: deckId,
          kind: content.kind,
          payload: content,
          status: 'active',
          source_excerpt: sourceExcerpt ?? null,
          // A manually added card enters the `new` queue (SPEC §4.1 step 6).
          ...newCardScheduling(new Date()),
        })
        .select(CARD_COLUMNS)
        .single();
      return unwrap(result);
    },
    onSuccess: card => invalidateCardCaches(queryClient, card.deck_id),
  });
}

/** Create several cards at once — what a multi-group cloze paste turns into. */
export function useCreateCards() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async ({
      deckId,
      payloads,
      sourceExcerpt,
    }: {
      deckId: string;
      payloads: CardPayload[];
      sourceExcerpt?: string | null;
    }) => {
      const contents = payloads.map(payload => CardPayload.parse(payload));
      const userId = await currentUserId();
      const scheduling = newCardScheduling(new Date());
      const result = await supabase
        .from('cards')
        .insert(
          contents.map(content => ({
            user_id: userId,
            deck_id: deckId,
            kind: content.kind,
            payload: content,
            status: 'active' as const,
            source_excerpt: sourceExcerpt ?? null,
            ...scheduling,
          })),
        )
        .select(CARD_COLUMNS);
      return unwrap(result);
    },
    onSuccess: (_cards, variables) => invalidateCardCaches(queryClient, variables.deckId),
  });
}

export function useUpdateCard() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async ({
      cardId,
      deckId: _deckId,
      payload,
    }: {
      cardId: string;
      deckId: string;
      payload: CardPayload;
    }) => {
      const content = CardPayload.parse(payload);
      const result = await supabase
        .from('cards')
        // Content only. Editing a card must never disturb its schedule — that is
        // the point of keeping content and scheduling in separate columns (§5.3).
        .update({ kind: content.kind, payload: content })
        .eq('id', cardId)
        .select(CARD_COLUMNS)
        .single();
      return unwrap(result);
    },
    onSuccess: card => invalidateCardCaches(queryClient, card.deck_id),
  });
}

/** Suspend or restore a card: out of the queue without losing its history. */
export function useSetCardStatus() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async ({
      cardIds,
      status,
      deckId: _deckId,
    }: {
      cardIds: string[];
      status: 'active' | 'suspended';
      deckId: string;
    }) => {
      const result = await supabase
        .from('cards')
        .update({ status })
        .in('id', cardIds)
        .select('id');
      return unwrap(result);
    },
    onSuccess: (_rows, variables) => invalidateCardCaches(queryClient, variables.deckId),
  });
}

export function useDeleteCards() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async ({
      cardIds,
      deckId: _deckId,
    }: {
      cardIds: string[];
      deckId: string;
    }) => {
      const result = await supabase.from('cards').delete().in('id', cardIds).select('id');
      return unwrap(result);
    },
    onSuccess: (_rows, variables) => invalidateCardCaches(queryClient, variables.deckId),
  });
}

function invalidateCardCaches(queryClient: QueryClient, deckId: string) {
  void queryClient.invalidateQueries({ queryKey: queryKeys.deck(deckId) });
  void queryClient.invalidateQueries({ queryKey: queryKeys.decks });
  void queryClient.invalidateQueries({ queryKey: ['queue'] });
}

// ---------------------------------------------------------------------------
// Practice queue
// ---------------------------------------------------------------------------

export type PracticeQueue = {
  cards: CardRow[];
  /** Cards not in this session because the daily cap is used up. */
  heldBackNew: number;
  newAllowanceLeft: number;
  /** Soonest due time among cards that are not due yet — the empty state. */
  nextDueAt: string | null;
  fetchedAt: string;
};

/**
 * The session's queue, assembled once.
 *
 * Three cheap reads — due cards, unseen cards, today's introductions — then
 * `buildQueue` applies the §6 policy. The counting query is separate because
 * "how many new cards has this user started today" is a fact about the whole
 * account, not about the deck being practised: switching decks must not hand
 * out a second day's worth of new cards.
 */
export function usePracticeQueue(deckId?: string) {
  const { data: profile } = useProfile();

  return useQuery({
    queryKey: queryKeys.queue(deckId),
    // Wait for the profile: the timezone decides where "today" starts, and
    // guessing UTC would hand out new cards early for most of the world.
    enabled: profile !== undefined,
    // A queue is a snapshot of a session. Refetching under the user mid-session
    // reorders the cards they are looking at.
    staleTime: Infinity,
    gcTime: 5 * 60_000,
    queryFn: async (): Promise<PracticeQueue> => {
      const now = new Date();
      const timeZone = resolveTimeZone(profile?.timezone);
      const dayStart = startOfStudyDay(now, timeZone);
      const dailyNewLimit = profile?.daily_new_limit ?? 20;

      const dueQuery = supabase
        .from('cards')
        .select(CARD_COLUMNS)
        .eq('status', 'active')
        // `new` cards are handled by the other stream; a new card's `due` is its
        // creation time, so without this they would appear twice and dodge the cap.
        .neq('fsrs_state', 'new')
        .lte('due', now.toISOString())
        .order('due', { ascending: true })
        .limit(QUEUE_FETCH_LIMIT);

      const freshQuery = supabase
        .from('cards')
        .select(CARD_COLUMNS)
        .eq('status', 'active')
        .eq('fsrs_state', 'new')
        .order('created_at', { ascending: true })
        .limit(Math.max(dailyNewLimit, 1));

      const introducedQuery = supabase
        .from('reviews')
        .select('id', { count: 'exact', head: true })
        .eq('state_before', 'new')
        .is('undone_at', null)
        .gte('reviewed_at', dayStart.toISOString());

      const upcomingQuery = supabase
        .from('cards')
        .select('due')
        .eq('status', 'active')
        .neq('fsrs_state', 'new')
        .gt('due', now.toISOString())
        .order('due', { ascending: true })
        .limit(1);

      if (deckId) {
        void dueQuery.eq('deck_id', deckId);
        void freshQuery.eq('deck_id', deckId);
        void upcomingQuery.eq('deck_id', deckId);
      }

      const [due, freshCards, introduced, upcoming] = await Promise.all([
        dueQuery,
        freshQuery,
        introducedQuery,
        upcomingQuery,
      ]);

      if (due.error) throw due.error;
      if (freshCards.error) throw freshCards.error;
      if (introduced.error) throw introduced.error;
      if (upcoming.error) throw upcoming.error;

      const introducedToday = introduced.count ?? 0;
      const allowance = remainingNewAllowance(dailyNewLimit, introducedToday);

      return {
        cards: buildQueue({
          due: due.data,
          fresh: freshCards.data,
          dailyNewLimit,
          introducedToday,
        }),
        heldBackNew: Math.max(0, freshCards.data.length - allowance),
        newAllowanceLeft: allowance,
        nextDueAt: upcoming.data[0]?.due ?? null,
        fetchedAt: now.toISOString(),
      };
    },
  });
}

// ---------------------------------------------------------------------------
// Rating and undo
// ---------------------------------------------------------------------------

export type ReviewCardInput = {
  card: CardRow;
  grade: Grade;
  durationMs?: number | null;
  /** The preview the user was shown, so the committed interval is that one. */
  preview?: SchedulePreview;
  deckId?: string;
};

/**
 * Rate a card.
 *
 * Optimistic by design (SPEC §8.3): the caller advances to the next card the
 * moment the button is pressed and this mutation catches up behind it. Practice
 * that waits a round trip per card is practice nobody does. On failure the
 * caller rolls back and toasts — and one failure in particular is expected
 * rather than exceptional, `isStaleCardError`, which means another tab already
 * rated this card.
 */
export function useReviewCard() {
  const queryClient = useQueryClient();
  const { data: profile } = useProfile();

  return useMutation({
    mutationFn: async ({ card, grade, durationMs, preview }: ReviewCardInput) => {
      const { next } = applyGrade(card, grade, new Date(), {
        durationMs: durationMs ?? null,
        preview,
        params: (profile?.fsrs_params as Record<string, never> | null) ?? null,
      });

      const result = await supabase.rpc('review_card', {
        p_card_id: card.id,
        p_rating: grade,
        // Null is a real value here — the card may have been rated before any
        // timer started, and `reviews.duration_ms` is nullable for exactly that.
        // Postgres cannot express argument nullability, so the generated types
        // say `number`; the cast says what the function actually accepts rather
        // than inventing a zero that would read as "answered instantly".
        p_duration_ms: (durationMs ?? null) as number,
        // Sent back exactly as PostgREST rendered it; this is the optimistic
        // concurrency token, and a re-formatted timestamp would never match.
        p_expected_updated_at: card.updated_at,
        p_next: next,
      });
      return unwrap(result);
    },

    onMutate: async ({ card, deckId }) => {
      const key = queryKeys.queue(deckId);
      await queryClient.cancelQueries({ queryKey: key });
      const previous = queryClient.getQueryData<PracticeQueue>(key);
      // Drop the card from the cached queue so a remount does not re-serve it.
      if (previous) {
        queryClient.setQueryData<PracticeQueue>(key, {
          ...previous,
          cards: previous.cards.filter(queued => queued.id !== card.id),
        });
      }
      return { previous, key };
    },

    onError: (_error, _variables, context) => {
      if (context?.previous) queryClient.setQueryData(context.key, context.previous);
    },

    onSuccess: card => {
      // Deliberately not invalidating the active queue: refetching mid-session
      // would reshuffle the cards the user is part-way through.
      void queryClient.invalidateQueries({ queryKey: queryKeys.decks });
      void queryClient.invalidateQueries({ queryKey: queryKeys.deckCards(card.deck_id) });
    },
  });
}

/**
 * Undo the last rating on a card (SPEC §4.2).
 *
 * Not optimistic: undo is the recovery path, and a recovery path that lies about
 * having worked is worse than one that takes 200ms.
 */
export function useUndoLastReview() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async ({ cardId }: { cardId: string; deckId?: string }) => {
      const result = await supabase.rpc('undo_last_review', { p_card_id: cardId });
      return unwrap(result);
    },
    onSuccess: card => {
      void queryClient.invalidateQueries({ queryKey: queryKeys.decks });
      void queryClient.invalidateQueries({ queryKey: queryKeys.deckCards(card.deck_id) });
    },
  });
}

// ---------------------------------------------------------------------------
// Dashboard
// ---------------------------------------------------------------------------

export type DueSummary = {
  dueNow: number;
  newAvailable: number;
  reviewedToday: number;
  nextDueAt: string | null;
};

/** The handful of numbers the dashboard shows. P3 owns anything more. */
export function useDueSummary() {
  const { data: profile } = useProfile();

  return useQuery({
    queryKey: ['queue', 'summary'],
    enabled: profile !== undefined,
    queryFn: async (): Promise<DueSummary> => {
      const now = new Date();
      const dayStart = startOfStudyDay(now, resolveTimeZone(profile?.timezone));

      const [due, fresh, reviewed, upcoming] = await Promise.all([
        supabase
          .from('cards')
          .select('id', { count: 'exact', head: true })
          .eq('status', 'active')
          .neq('fsrs_state', 'new')
          .lte('due', now.toISOString()),
        supabase
          .from('cards')
          .select('id', { count: 'exact', head: true })
          .eq('status', 'active')
          .eq('fsrs_state', 'new'),
        supabase
          .from('reviews')
          .select('id', { count: 'exact', head: true })
          .is('undone_at', null)
          .gte('reviewed_at', dayStart.toISOString()),
        supabase
          .from('cards')
          .select('due')
          .eq('status', 'active')
          .neq('fsrs_state', 'new')
          .gt('due', now.toISOString())
          .order('due', { ascending: true })
          .limit(1),
      ]);

      if (due.error) throw due.error;
      if (fresh.error) throw fresh.error;
      if (reviewed.error) throw reviewed.error;
      if (upcoming.error) throw upcoming.error;

      return {
        dueNow: due.count ?? 0,
        newAvailable: Math.min(
          fresh.count ?? 0,
          remainingNewAllowance(profile?.daily_new_limit ?? 20, 0),
        ),
        reviewedToday: reviewed.count ?? 0,
        nextDueAt: upcoming.data[0]?.due ?? null,
      };
    },
  });
}

export type { CardKind };
