import {
  useMutation,
  useQuery,
  useQueryClient,
  type QueryClient,
} from '@tanstack/react-query';
import { supabase } from './supabase';
import { CardPayload, DeckInput, Grade, ProfileSettings, type CardKind } from './schemas';
import { applyGrade, newCardScheduling, type SchedulePreview } from './fsrs';
import {
  GENERATION_QUOTA,
  monthWindow,
  quotaCountFilter,
  remainingGenerations,
} from './quota';
import {
  addStudyDays,
  resolveTimeZone,
  startOfStudyDay,
  studyDayKey,
  studyDayStart,
} from './day';
import { buildQueue, remainingNewAllowance } from './queue';
import {
  countable,
  forecast,
  HEATMAP_DAYS,
  memoryStrength,
  stateDistribution,
  type CountedReviews,
  type ForecastDay,
  type MemoryStrength,
  type StateDistribution,
} from './progress';
import type { Database } from '@/types/database';

/**
 * Every read and write the app performs, as TanStack Query hooks over
 * supabase-js. Thin on purpose: policy lives in fsrs.ts and queue.ts, atomicity
 * lives in the `review_card` RPC, and this file is the wiring between them.
 *
 * Two rules hold throughout:
 *   - Validate with the shared Zod schemas *before* the network call, so bad
 *     data fails locally with a field-level message instead of as a 400.
 *   - Never send `user_id` from a form. It comes from the session, and RLS
 *     rejects anything else anyway (SPEC §5.7).
 */

export type CardRow = Database['public']['Tables']['cards']['Row'];
export type DeckRow = Database['public']['Tables']['decks']['Row'];
export type ProfileRow = Database['public']['Tables']['profiles']['Row'];

/** Query keys, as SPEC §8.3. Deck-scoped data nests under `['deck', id]` so one
 *  invalidation covers the deck and its cards. */
export const queryKeys = {
  decks: ['decks'] as const,
  deck: (deckId: string) => ['deck', deckId] as const,
  deckCards: (deckId: string) => ['deck', deckId, 'cards'] as const,
  queue: (deckId?: string) => ['queue', deckId ?? 'all'] as const,
  profile: ['profile'] as const,
  /** Drafts waiting at the review gate, and only those. */
  deckDrafts: (deckId: string) => ['deck', deckId, 'drafts'] as const,
  quota: ['quota'] as const,
  /** Everything /progress reads, so one `['stats']` invalidation covers it. */
  statsHistory: (days: number) => ['stats', 'history', days] as const,
  statsForecast: (days: number) => ['stats', 'forecast', days] as const,
  statsRetention: (days: number) => ['stats', 'retention', days] as const,
  statsCards: ['stats', 'cards'] as const,
};

/**
 * Error codes raised by supabase/migrations/20260812093000_review_card.sql.
 * A stale rating is an expected outcome, not a crash: it means the card was
 * already rated somewhere else.
 */
export const RPC_ERROR = {
  staleCard: 'PT409',
  notFound: 'PT404',
} as const;

export function isStaleCardError(error: unknown): boolean {
  return (error as { code?: string } | null)?.code === RPC_ERROR.staleCard;
}

/**
 * How many due cards one queue fetch pulls. A session is not a spreadsheet;
 * beyond a few hundred cards the number stops being actionable, and the next
 * fetch picks up whatever is left. Reviews are never *dropped* by this — they
 * are still due, and still first in line.
 */
export const QUEUE_FETCH_LIMIT = 400;

/**
 * Cards are selected whole. Every column except `user_id` is used somewhere —
 * content to render, scheduling to grade against, `updated_at` as the
 * concurrency token — and a hand-maintained column list is one more place to
 * forget a migration. supabase-js also infers row types only from a literal
 * selector, so `'*'` is what keeps `CardRow` honest.
 */
const CARD_COLUMNS = '*';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

type PostgrestResult<T> = { data: T | null; error: { message: string } | null };

/** Throw supabase-js errors so TanStack Query sees a rejected promise. */
function unwrap<T>(result: PostgrestResult<T>): T {
  if (result.error) throw result.error;
  if (result.data === null) throw new Error('The server returned no row.');
  return result.data;
}

/** Same, for reads where "no row" is a legitimate answer. */
function unwrapMaybe<T>(result: PostgrestResult<T>): T | null {
  if (result.error) throw result.error;
  return result.data;
}

/** The signed-in user's id. Mutations need it; RLS will not accept any other. */
async function currentUserId(): Promise<string> {
  const { data, error } = await supabase.auth.getSession();
  if (error) throw error;
  const userId = data.session?.user.id;
  if (!userId) throw new Error('You are signed out. Sign in and try again.');
  return userId;
}

/**
 * A card's content, validated.
 *
 * Card payloads are untrusted (§10): generated by an LLM in P2, and stored as
 * free-form jsonb. Anything that fails the schema is surfaced as a broken card
 * the user can edit or delete, never rendered on a guess.
 */
export function parseCardPayload(row: Pick<CardRow, 'payload'>): CardPayload | null {
  const parsed = CardPayload.safeParse(row.payload);
  return parsed.success ? parsed.data : null;
}

// ---------------------------------------------------------------------------
// Profile
// ---------------------------------------------------------------------------

export function useProfile() {
  return useQuery({
    queryKey: queryKeys.profile,
    queryFn: async (): Promise<ProfileRow | null> => {
      const userId = await currentUserId();
      const result = await supabase
        .from('profiles')
        .select('*')
        .eq('id', userId)
        .maybeSingle();
      return unwrapMaybe(result);
    },
    // The timezone here decides every day boundary; a stale copy shifts the
    // new-card cap. Cheap row, so just keep it fresh.
    staleTime: 60_000,
  });
}

export function useUpdateProfile() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (input: ProfileSettings) => {
      const settings = ProfileSettings.parse(input);
      const userId = await currentUserId();
      const result = await supabase
        .from('profiles')
        .update({
          display_name: settings.display_name?.trim() || null,
          timezone: settings.timezone,
          daily_new_limit: settings.daily_new_limit,
        })
        .eq('id', userId)
        .select()
        .single();
      return unwrap(result);
    },
    onSuccess: profile => {
      queryClient.setQueryData(queryKeys.profile, profile);
      // The day boundary and the cap both moved; every queue is now suspect.
      void queryClient.invalidateQueries({ queryKey: ['queue'] });
    },
  });
}

// ---------------------------------------------------------------------------
// Decks
// ---------------------------------------------------------------------------

export type DeckWithCounts = DeckRow & {
  cardCount: number;
  dueCount: number;
  newCount: number;
  /** Generated cards still waiting at the review gate (SPEC §4.1 step 5). */
  draftCount: number;
};

/**
 * Decks with their card, due and new counts.
 *
 * The counts come from one card fetch rather than three aggregate round trips:
 * `select deck_id, status, fsrs_state, due` over a user's own cards is small and
 * index-covered, and it keeps the deck list a single request.
 */
export function useDecks() {
  return useQuery({
    queryKey: queryKeys.decks,
    queryFn: async (): Promise<DeckWithCounts[]> => {
      const decks = unwrap(
        await supabase
          .from('decks')
          .select('*')
          .neq('status', 'failed')
          .order('updated_at', { ascending: false }),
      );

      const counters = unwrap(
        await supabase
          .from('cards')
          .select('deck_id, status, fsrs_state, due')
          // Drafts come along for the ride: a deck abandoned part-way through
          // the review gate has to be findable from the deck list, and it has no
          // active cards to advertise itself with (SPEC §4.1).
          .in('status', ['active', 'draft']),
      );

      const now = Date.now();
      type Bucket = { cards: number; due: number; fresh: number; drafts: number };
      const byDeck = new Map<string, Bucket>();
      for (const card of counters) {
        const bucket = byDeck.get(card.deck_id) ?? {
          cards: 0,
          due: 0,
          fresh: 0,
          drafts: 0,
        };
        if (card.status === 'draft') {
          bucket.drafts += 1;
        } else {
          bucket.cards += 1;
          if (card.fsrs_state === 'new') bucket.fresh += 1;
          else if (new Date(card.due).getTime() <= now) bucket.due += 1;
        }
        byDeck.set(card.deck_id, bucket);
      }

      return decks.map(deck => {
        const bucket = byDeck.get(deck.id);
        return {
          ...deck,
          cardCount: bucket?.cards ?? 0,
          dueCount: bucket?.due ?? 0,
          newCount: bucket?.fresh ?? 0,
          draftCount: bucket?.drafts ?? 0,
        };
      });
    },
  });
}

export function useDeck(deckId: string | undefined) {
  return useQuery({
    queryKey: queryKeys.deck(deckId ?? ''),
    enabled: Boolean(deckId),
    queryFn: async (): Promise<DeckRow> => {
      const result = await supabase.from('decks').select('*').eq('id', deckId!).single();
      return unwrap(result);
    },
  });
}

export function useCreateDeck() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (input: DeckInput) => {
      const deck = DeckInput.parse(input);
      const userId = await currentUserId();
      const result = await supabase
        .from('decks')
        .insert({
          user_id: userId,
          title: deck.title,
          description: deck.description || null,
          source: 'manual',
          status: 'active',
        })
        .select()
        .single();
      return unwrap(result);
    },
    onSuccess: () => queryClient.invalidateQueries({ queryKey: queryKeys.decks }),
  });
}

export function useUpdateDeck() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async ({ deckId, ...input }: DeckInput & { deckId: string }) => {
      const deck = DeckInput.parse(input);
      const result = await supabase
        .from('decks')
        .update({ title: deck.title, description: deck.description || null })
        .eq('id', deckId)
        .select()
        .single();
      return unwrap(result);
    },
    onSuccess: deck => {
      queryClient.setQueryData(queryKeys.deck(deck.id), deck);
      void queryClient.invalidateQueries({ queryKey: queryKeys.decks });
    },
  });
}

export function useDeleteDeck() {
  const queryClient = useQueryClient();
  return useMutation({
    // Cards cascade with the deck (§5.3 references ... on delete cascade), so
    // this is genuinely destructive — the caller must confirm first (§10).
    mutationFn: async (deckId: string) => {
      unwrap(await supabase.from('decks').delete().eq('id', deckId).select('id'));
      return deckId;
    },
    onSuccess: deckId => {
      queryClient.removeQueries({ queryKey: queryKeys.deck(deckId) });
      void queryClient.invalidateQueries({ queryKey: queryKeys.decks });
      void queryClient.invalidateQueries({ queryKey: ['queue'] });
    },
  });
}

// ---------------------------------------------------------------------------
// Cards
// ---------------------------------------------------------------------------

export function useCards(deckId: string | undefined) {
  return useQuery({
    queryKey: queryKeys.deckCards(deckId ?? ''),
    enabled: Boolean(deckId),
    queryFn: async (): Promise<CardRow[]> => {
      const result = await supabase
        .from('cards')
        .select(CARD_COLUMNS)
        .eq('deck_id', deckId!)
        .neq('status', 'archived')
        .order('created_at', { ascending: true });
      return unwrap(result);
    },
  });
}

export type CreateCardInput = {
  deckId: string;
  payload: CardPayload;
  sourceExcerpt?: string | null;
};

export function useCreateCard() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async ({ deckId, payload, sourceExcerpt }: CreateCardInput) => {
      const content = CardPayload.parse(payload);
      const userId = await currentUserId();
      const result = await supabase
        .from('cards')
        .insert({
          user_id: userId,
          deck_id: deckId,
          kind: content.kind,
          payload: content,
          status: 'active',
          source_excerpt: sourceExcerpt ?? null,
          // A manually added card enters the `new` queue (SPEC §4.1 step 6).
          ...newCardScheduling(new Date()),
        })
        .select(CARD_COLUMNS)
        .single();
      return unwrap(result);
    },
    onSuccess: card => invalidateCardCaches(queryClient, card.deck_id),
  });
}

/** Create several cards at once — what a multi-group cloze paste turns into. */
export function useCreateCards() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async ({
      deckId,
      payloads,
      sourceExcerpt,
    }: {
      deckId: string;
      payloads: CardPayload[];
      sourceExcerpt?: string | null;
    }) => {
      const contents = payloads.map(payload => CardPayload.parse(payload));
      const userId = await currentUserId();
      const scheduling = newCardScheduling(new Date());
      const result = await supabase
        .from('cards')
        .insert(
          contents.map(content => ({
            user_id: userId,
            deck_id: deckId,
            kind: content.kind,
            payload: content,
            status: 'active' as const,
            source_excerpt: sourceExcerpt ?? null,
            ...scheduling,
          })),
        )
        .select(CARD_COLUMNS);
      return unwrap(result);
    },
    onSuccess: (_cards, variables) => invalidateCardCaches(queryClient, variables.deckId),
  });
}

export function useUpdateCard() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async ({
      cardId,
      deckId: _deckId,
      payload,
    }: {
      cardId: string;
      deckId: string;
      payload: CardPayload;
    }) => {
      const content = CardPayload.parse(payload);
      const result = await supabase
        .from('cards')
        // Content only. Editing a card must never disturb its schedule — that is
        // the point of keeping content and scheduling in separate columns (§5.3).
        .update({ kind: content.kind, payload: content })
        .eq('id', cardId)
        .select(CARD_COLUMNS)
        .single();
      return unwrap(result);
    },
    onSuccess: card => invalidateCardCaches(queryClient, card.deck_id),
  });
}

/** Suspend or restore a card: out of the queue without losing its history. */
export function useSetCardStatus() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async ({
      cardIds,
      status,
      deckId: _deckId,
    }: {
      cardIds: string[];
      status: 'active' | 'suspended';
      deckId: string;
    }) => {
      const result = await supabase
        .from('cards')
        .update({ status })
        .in('id', cardIds)
        .select('id');
      return unwrap(result);
    },
    onSuccess: (_rows, variables) => invalidateCardCaches(queryClient, variables.deckId),
  });
}

export function useDeleteCards() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async ({
      cardIds,
      deckId: _deckId,
    }: {
      cardIds: string[];
      deckId: string;
    }) => {
      const result = await supabase.from('cards').delete().in('id', cardIds).select('id');
      return unwrap(result);
    },
    onSuccess: (_rows, variables) => invalidateCardCaches(queryClient, variables.deckId),
  });
}

function invalidateCardCaches(queryClient: QueryClient, deckId: string) {
  void queryClient.invalidateQueries({ queryKey: queryKeys.deck(deckId) });
  void queryClient.invalidateQueries({ queryKey: queryKeys.decks });
  void queryClient.invalidateQueries({ queryKey: ['queue'] });
}

// ---------------------------------------------------------------------------
// Practice queue
// ---------------------------------------------------------------------------

export type PracticeQueue = {
  cards: CardRow[];
  /** Cards not in this session because the daily cap is used up. */
  heldBackNew: number;
  newAllowanceLeft: number;
  /** Soonest due time among cards that are not due yet — the empty state. */
  nextDueAt: string | null;
  fetchedAt: string;
};

/**
 * The session's queue, assembled once.
 *
 * Three cheap reads — due cards, unseen cards, today's introductions — then
 * `buildQueue` applies the §6 policy. The counting query is separate because
 * "how many new cards has this user started today" is a fact about the whole
 * account, not about the deck being practised: switching decks must not hand
 * out a second day's worth of new cards.
 */
export function usePracticeQueue(deckId?: string) {
  const { data: profile } = useProfile();

  return useQuery({
    queryKey: queryKeys.queue(deckId),
    // Wait for the profile: the timezone decides where "today" starts, and
    // guessing UTC would hand out new cards early for most of the world.
    enabled: profile !== undefined,
    // A queue is a snapshot of a session. Refetching under the user mid-session
    // reorders the cards they are looking at.
    staleTime: Infinity,
    gcTime: 5 * 60_000,
    queryFn: async (): Promise<PracticeQueue> => {
      const now = new Date();
      const timeZone = resolveTimeZone(profile?.timezone);
      const dayStart = startOfStudyDay(now, timeZone);
      const dailyNewLimit = profile?.daily_new_limit ?? 20;

      const dueQuery = supabase
        .from('cards')
        .select(CARD_COLUMNS)
        .eq('status', 'active')
        // `new` cards are handled by the other stream; a new card's `due` is its
        // creation time, so without this they would appear twice and dodge the cap.
        .neq('fsrs_state', 'new')
        .lte('due', now.toISOString())
        .order('due', { ascending: true })
        .limit(QUEUE_FETCH_LIMIT);

      const freshQuery = supabase
        .from('cards')
        .select(CARD_COLUMNS)
        .eq('status', 'active')
        .eq('fsrs_state', 'new')
        .order('created_at', { ascending: true })
        .limit(Math.max(dailyNewLimit, 1));

      const introducedQuery = supabase
        .from('reviews')
        .select('id', { count: 'exact', head: true })
        .eq('state_before', 'new')
        .is('undone_at', null)
        .gte('reviewed_at', dayStart.toISOString());

      const upcomingQuery = supabase
        .from('cards')
        .select('due')
        .eq('status', 'active')
        .neq('fsrs_state', 'new')
        .gt('due', now.toISOString())
        .order('due', { ascending: true })
        .limit(1);

      if (deckId) {
        void dueQuery.eq('deck_id', deckId);
        void freshQuery.eq('deck_id', deckId);
        void upcomingQuery.eq('deck_id', deckId);
      }

      const [due, freshCards, introduced, upcoming] = await Promise.all([
        dueQuery,
        freshQuery,
        introducedQuery,
        upcomingQuery,
      ]);

      if (due.error) throw due.error;
      if (freshCards.error) throw freshCards.error;
      if (introduced.error) throw introduced.error;
      if (upcoming.error) throw upcoming.error;

      const introducedToday = introduced.count ?? 0;
      const allowance = remainingNewAllowance(dailyNewLimit, introducedToday);

      return {
        cards: buildQueue({
          due: due.data,
          fresh: freshCards.data,
          dailyNewLimit,
          introducedToday,
        }),
        heldBackNew: Math.max(0, freshCards.data.length - allowance),
        newAllowanceLeft: allowance,
        nextDueAt: upcoming.data[0]?.due ?? null,
        fetchedAt: now.toISOString(),
      };
    },
  });
}

// ---------------------------------------------------------------------------
// Rating and undo
// ---------------------------------------------------------------------------

export type ReviewCardInput = {
  card: CardRow;
  grade: Grade;
  durationMs?: number | null;
  /** The preview the user was shown, so the committed interval is that one. */
  preview?: SchedulePreview;
  deckId?: string;
};

/**
 * Rate a card.
 *
 * Optimistic by design (SPEC §8.3): the caller advances to the next card the
 * moment the button is pressed and this mutation catches up behind it. Practice
 * that waits a round trip per card is practice nobody does. On failure the
 * caller rolls back and toasts — and one failure in particular is expected
 * rather than exceptional, `isStaleCardError`, which means another tab already
 * rated this card.
 */
export function useReviewCard() {
  const queryClient = useQueryClient();
  const { data: profile } = useProfile();

  return useMutation({
    mutationFn: async ({ card, grade, durationMs, preview }: ReviewCardInput) => {
      const { next } = applyGrade(card, grade, new Date(), {
        durationMs: durationMs ?? null,
        preview,
        params: (profile?.fsrs_params as Record<string, never> | null) ?? null,
      });

      const result = await supabase.rpc('review_card', {
        p_card_id: card.id,
        p_rating: grade,
        // Null is a real value here — the card may have been rated before any
        // timer started, and `reviews.duration_ms` is nullable for exactly that.
        // Postgres cannot express argument nullability, so the generated types
        // say `number`; the cast says what the function actually accepts rather
        // than inventing a zero that would read as "answered instantly".
        p_duration_ms: (durationMs ?? null) as number,
        // Sent back exactly as PostgREST rendered it; this is the optimistic
        // concurrency token, and a re-formatted timestamp would never match.
        p_expected_updated_at: card.updated_at,
        p_next: next,
      });
      return unwrap(result);
    },

    onMutate: async ({ card, deckId }) => {
      const key = queryKeys.queue(deckId);
      await queryClient.cancelQueries({ queryKey: key });
      const previous = queryClient.getQueryData<PracticeQueue>(key);
      // Drop the card from the cached queue so a remount does not re-serve it.
      if (previous) {
        queryClient.setQueryData<PracticeQueue>(key, {
          ...previous,
          cards: previous.cards.filter(queued => queued.id !== card.id),
        });
      }
      return { previous, key };
    },

    onError: (_error, _variables, context) => {
      if (context?.previous) queryClient.setQueryData(context.key, context.previous);
    },

    onSuccess: card => {
      // Deliberately not invalidating the active queue: refetching mid-session
      // would reshuffle the cards the user is part-way through.
      void queryClient.invalidateQueries({ queryKey: queryKeys.decks });
      void queryClient.invalidateQueries({ queryKey: queryKeys.deckCards(card.deck_id) });
      // Every /progress figure is derived from the row this just wrote.
      void queryClient.invalidateQueries({ queryKey: ['stats'] });
    },
  });
}

/**
 * Undo the last rating on a card (SPEC §4.2).
 *
 * Not optimistic: undo is the recovery path, and a recovery path that lies about
 * having worked is worse than one that takes 200ms.
 */
export function useUndoLastReview() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async ({ cardId }: { cardId: string; deckId?: string }) => {
      const result = await supabase.rpc('undo_last_review', { p_card_id: cardId });
      return unwrap(result);
    },
    onSuccess: card => {
      void queryClient.invalidateQueries({ queryKey: queryKeys.decks });
      void queryClient.invalidateQueries({ queryKey: queryKeys.deckCards(card.deck_id) });
      // The tombstoned rating drops out of every metric; today's heatmap cell
      // has to go down by one straight away or undo looks like it did nothing.
      void queryClient.invalidateQueries({ queryKey: ['stats'] });
    },
  });
}

// ---------------------------------------------------------------------------
// Dashboard
// ---------------------------------------------------------------------------

export type DueSummary = {
  dueNow: number;
  newAvailable: number;
  reviewedToday: number;
  nextDueAt: string | null;
};

/** The handful of numbers the dashboard shows. P3 owns anything more. */
export function useDueSummary() {
  const { data: profile } = useProfile();

  return useQuery({
    queryKey: ['queue', 'summary'],
    enabled: profile !== undefined,
    queryFn: async (): Promise<DueSummary> => {
      const now = new Date();
      const dayStart = startOfStudyDay(now, resolveTimeZone(profile?.timezone));

      const [due, fresh, reviewed, upcoming] = await Promise.all([
        supabase
          .from('cards')
          .select('id', { count: 'exact', head: true })
          .eq('status', 'active')
          .neq('fsrs_state', 'new')
          .lte('due', now.toISOString()),
        supabase
          .from('cards')
          .select('id', { count: 'exact', head: true })
          .eq('status', 'active')
          .eq('fsrs_state', 'new'),
        supabase
          .from('reviews')
          .select('id', { count: 'exact', head: true })
          .is('undone_at', null)
          .gte('reviewed_at', dayStart.toISOString()),
        supabase
          .from('cards')
          .select('due')
          .eq('status', 'active')
          .neq('fsrs_state', 'new')
          .gt('due', now.toISOString())
          .order('due', { ascending: true })
          .limit(1),
      ]);

      if (due.error) throw due.error;
      if (fresh.error) throw fresh.error;
      if (reviewed.error) throw reviewed.error;
      if (upcoming.error) throw upcoming.error;

      return {
        dueNow: due.count ?? 0,
        newAvailable: Math.min(
          fresh.count ?? 0,
          remainingNewAllowance(profile?.daily_new_limit ?? 20, 0),
        ),
        reviewedToday: reviewed.count ?? 0,
        nextDueAt: upcoming.data[0]?.due ?? null,
      };
    },
  });
}

// ---------------------------------------------------------------------------
// Generation: drafts, the review gate, and quota
//
// The cards themselves are written by the Edge Function, not from here
// (SPEC §7.1) — it holds the caller's JWT and inserts under the same policies.
// What the client owns is everything after: reading the drafts back, accepting
// or rejecting them, and showing how much of the monthly allowance is left.
// ---------------------------------------------------------------------------

/** The drafts a generation left behind, oldest first — the review gate's queue. */
export function useDraftCards(deckId: string | undefined) {
  return useQuery({
    queryKey: queryKeys.deckDrafts(deckId ?? ''),
    enabled: Boolean(deckId),
    queryFn: async (): Promise<CardRow[]> => {
      const result = await supabase
        .from('cards')
        .select(CARD_COLUMNS)
        .eq('deck_id', deckId!)
        .eq('status', 'draft')
        .order('created_at', { ascending: true });
      return unwrap(result);
    },
    // A generation may still be streaming into this deck; a stale list here is
    // the difference between "resume where you left off" and "half your cards
    // are missing".
    staleTime: 0,
  });
}

/**
 * Accept drafts: `draft` → `active`, and nothing else.
 *
 * An update, not an insert — the rows already exist, written as they streamed
 * in — and it deliberately leaves the scheduling columns alone. The card was
 * created with fresh-card state, so accepting it drops it straight into the
 * `new` queue where P1's practice loop finds it, with no change to fsrs.ts or
 * `review_card` (SPEC §4.1 step 6).
 */
export function useAcceptDrafts() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async ({
      cardIds,
      deckId: _deckId,
    }: {
      cardIds: string[];
      deckId: string;
    }) => {
      const result = await supabase
        .from('cards')
        .update({ status: 'active' })
        .in('id', cardIds)
        .eq('status', 'draft')
        .select('id');
      return unwrap(result);
    },
    onSuccess: (_rows, variables) => invalidateCardCaches(queryClient, variables.deckId),
  });
}

/**
 * Close the gate: the deck becomes an ordinary deck, and the audit row learns
 * how many of its cards survived.
 *
 * `cards_accepted` is counted from the cards rather than tallied in the UI, so
 * resuming an abandoned gate later corrects the number instead of double
 * counting it. SPEC §13 (2) measures the product on this figure — "fewer than
 * 20% rejected" — which is only worth measuring if it reflects the deck.
 */
export function useFinishReviewGate() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async ({ deckId }: { deckId: string }) => {
      const accepted = await supabase
        .from('cards')
        .select('id', { count: 'exact', head: true })
        .eq('deck_id', deckId)
        .eq('status', 'active');
      if (accepted.error) throw accepted.error;

      const deck = await supabase
        .from('decks')
        .update({ status: 'active' })
        .eq('id', deckId)
        .select()
        .single();

      // Best effort by design: the generation row is an audit trail, and failing
      // to stamp it must not leave the user staring at a deck that will not
      // leave the review gate.
      await supabase
        .from('generations')
        .update({ cards_accepted: accepted.count ?? 0 })
        .eq('deck_id', deckId);

      return unwrap(deck);
    },
    onSuccess: deck => {
      queryClient.setQueryData(queryKeys.deck(deck.id), deck);
      invalidateCardCaches(queryClient, deck.id);
    },
  });
}

export type QuotaUsage = {
  used: number;
  remaining: number;
  limit: number;
  /** When the allowance resets — the 1st of next month, UTC. */
  resetsAt: string;
};

/**
 * How much of the monthly allowance is gone (SPEC §4.1 step 3).
 *
 * Advisory: the Edge Function counts the same rows with the same filter and is
 * the only thing that can actually refuse. Showing the number here is what stops
 * the refusal being a surprise at submit time.
 */
export function useQuotaUsage() {
  return useQuery({
    queryKey: queryKeys.quota,
    queryFn: async (): Promise<QuotaUsage> => {
      const now = new Date();
      const month = monthWindow(now);
      const result = await supabase
        .from('generations')
        .select('id', { count: 'exact', head: true })
        .gte('created_at', month.start.toISOString())
        .lt('created_at', month.end.toISOString())
        .or(quotaCountFilter(now));
      if (result.error) throw result.error;

      const used = result.count ?? 0;
      return {
        used,
        remaining: remainingGenerations(used),
        limit: GENERATION_QUOTA.monthlyGenerations,
        resetsAt: month.end.toISOString(),
      };
    },
    staleTime: 30_000,
  });
}

// ---------------------------------------------------------------------------
// Progress (SPEC §4.4)
//
// Four reads, keyed under `['stats', …]` per §8.3 so one invalidation after a
// rating refreshes the whole page. Three of them wait for `useProfile` the way
// `usePracticeQueue` does: the timezone decides where every day starts, and
// guessing UTC produces a heatmap that is subtly wrong for most of the world.
//
// `staleTime` is a minute throughout. This is a dashboard, not a session — it
// should reflect the last review without refetching on every focus change.
// ---------------------------------------------------------------------------

const STATS_STALE_TIME = 60_000;

export type ReviewDayCount =
  Database['public']['Functions']['review_day_counts']['Returns'][number];

export type ReviewHistory = {
  timeZone: string;
  /** The study day the client is in — the heatmap's last cell. */
  today: string;
  rows: ReviewDayCount[];
  /** Reviews per study day, the shape `heatmapGrid` and `streaks` want. */
  counts: Map<string, number>;
  total: number;
};

/**
 * A year of daily counts, aggregated in Postgres.
 *
 * The aggregate is the point of P3's migration: a serious user's year is
 * ~70,000 review rows and this returns at most 365 of them. See
 * supabase/migrations/20260812210000_progress_stats.sql for why the day bucket
 * is written the way it is.
 */
export function useReviewHistory(days: number = HEATMAP_DAYS) {
  const { data: profile } = useProfile();

  return useQuery({
    queryKey: queryKeys.statsHistory(days),
    enabled: profile !== undefined,
    staleTime: STATS_STALE_TIME,
    queryFn: async (): Promise<ReviewHistory> => {
      const timeZone = resolveTimeZone(profile?.timezone);
      const today = studyDayKey(new Date(), timeZone);
      const from = studyDayStart(addStudyDays(today, -(days - 1)), timeZone);

      const rows = unwrap(
        await supabase.rpc('review_day_counts', {
          p_timezone: timeZone,
          p_from: from.toISOString(),
        }),
      );

      let total = 0;
      const counts = new Map<string, number>();
      for (const row of rows) {
        counts.set(row.day, row.reviews);
        total += row.reviews;
      }
      return { timeZone, today, rows, counts, total };
    },
  });
}

export type DueForecast = {
  timeZone: string;
  takenAt: string;
  buckets: ForecastDay[];
};

/**
 * What the next `days` study days cost.
 *
 * Bucketed on the client rather than in SQL: `cards` is small next to `reviews`
 * — this fetches only active, non-new cards inside the horizon — and one fewer
 * function is one fewer thing to close to `anon`.
 *
 * Day 0 has to equal what `/practice` would serve this minute, so it carries the
 * overdue cards *and* today's remaining new-card allowance, counted by the same
 * §6 policy the queue uses.
 */
export function useDueForecast(days = 30) {
  const { data: profile } = useProfile();

  return useQuery({
    queryKey: queryKeys.statsForecast(days),
    enabled: profile !== undefined,
    staleTime: STATS_STALE_TIME,
    queryFn: async (): Promise<DueForecast> => {
      const now = new Date();
      const timeZone = resolveTimeZone(profile?.timezone);
      const dailyNewLimit = profile?.daily_new_limit ?? 20;
      const horizon = studyDayStart(
        addStudyDays(studyDayKey(now, timeZone), days),
        timeZone,
      );

      const [scheduled, fresh, introduced] = await Promise.all([
        supabase
          .from('cards')
          .select('due, fsrs_state')
          .eq('status', 'active')
          // A new card's `due` is its creation time; new cards are counted
          // through the daily cap below, never through the schedule.
          .neq('fsrs_state', 'new')
          .lt('due', horizon.toISOString()),
        supabase
          .from('cards')
          .select('id', { count: 'exact', head: true })
          .eq('status', 'active')
          .eq('fsrs_state', 'new'),
        supabase
          .from('reviews')
          .select('id', { count: 'exact', head: true })
          .eq('state_before', 'new')
          .is('undone_at', null)
          .gte('reviewed_at', startOfStudyDay(now, timeZone).toISOString()),
      ]);

      if (scheduled.error) throw scheduled.error;
      if (fresh.error) throw fresh.error;
      if (introduced.error) throw introduced.error;

      const newToday = Math.min(
        fresh.count ?? 0,
        remainingNewAllowance(dailyNewLimit, introduced.count ?? 0),
      );

      return {
        timeZone,
        takenAt: now.toISOString(),
        buckets: forecast(scheduled.data, now, days, { timeZone, newToday }),
      };
    },
  });
}

export type CardStates = {
  distribution: StateDistribution;
  strength: MemoryStrength;
};

/**
 * The card-state mix, and the mean stability and difficulty behind it.
 *
 * Not gated on the profile: nothing here is bucketed by day, so there is no
 * timezone to get wrong, and waiting on a query it does not use would only make
 * the page slower. Stability and difficulty have to come back as values rather
 * than counts — a mean cannot be made from `head: true` — and this is the same
 * fetch shape `useDecks` already performs over the card table.
 */
export function useCardStates() {
  return useQuery({
    queryKey: queryKeys.statsCards,
    staleTime: STATS_STALE_TIME,
    queryFn: async (): Promise<CardStates> => {
      const rows = unwrap(
        await supabase
          .from('cards')
          .select('fsrs_state, stability, difficulty')
          .eq('status', 'active'),
      );
      return { distribution: stateDistribution(rows), strength: memoryStrength(rows) };
    },
  });
}

export type RetentionHistory = {
  timeZone: string;
  today: string;
  from: Date;
  to: Date;
  /** Undone ratings already dropped — twice, and deliberately. */
  reviews: CountedReviews;
};

/**
 * Reviews inside the widest retention window, fetched once.
 *
 * One request rather than three: 7, 30 and 90 days are nested, so the caller
 * slices this with `retention()` rather than asking the server the same question
 * at three lengths. Six columns, because row count is the cost here — a heavy
 * user's 90 days is thousands of rows, and `select *` would drag the whole FSRS
 * snapshot along with each one.
 *
 * `undone_at` is filtered server-side *and* selected, so `countable` has
 * something real to filter and the exclusion is provable rather than assumed.
 */
export function useRetention(days = 90) {
  const { data: profile } = useProfile();

  return useQuery({
    queryKey: queryKeys.statsRetention(days),
    enabled: profile !== undefined,
    staleTime: STATS_STALE_TIME,
    queryFn: async (): Promise<RetentionHistory> => {
      const now = new Date();
      const timeZone = resolveTimeZone(profile?.timezone);
      const today = studyDayKey(now, timeZone);
      const from = studyDayStart(addStudyDays(today, -(days - 1)), timeZone);

      const rows = unwrap(
        await supabase
          .from('reviews')
          .select(
            'rating, state_before, reviewed_at, undone_at, stability_after, difficulty_after',
          )
          .is('undone_at', null)
          .gte('reviewed_at', from.toISOString())
          .order('reviewed_at', { ascending: true }),
      );

      return { timeZone, today, from, to: now, reviews: countable(rows) };
    },
  });
}

export type { CardKind };
