#!/usr/bin/env node
/**
 * Fills the demo account with a plausible life: four generated decks and about
 * two months of review history.
 *
 *   npm run demo:seed            # refuses if the account already has decks
 *   npm run demo:seed -- --reset # deletes them first, then rebuilds
 *
 * Why this exists: a stranger who signs up sees an empty app, and the product's
 * argument does not survive an empty app (P4 task 7). The demo account is what a
 * first visit can be pointed at — so it has to show the flagship flow's *output*,
 * which means the cards are really generated by the Edge Function, not typed here.
 *
 * Three rules it follows, all of them load-bearing:
 *
 *  1. **It signs in as the demo user and stays inside RLS.** No secret key, no
 *     `service_role`. Every row it writes is a row the app itself could have
 *     written, which is what makes the result a demonstration rather than a
 *     mock-up.
 *  2. **It drives the real generation pipeline** — the same POST, the same SSE
 *     decoder, the same `StreamEvent` schema as `useGenerateCards`. If the
 *     function is misconfigured this script fails, and that is the point.
 *  3. **The history is replayed, not invented.** Every rating goes through
 *     `applyGrade`, and the card's final scheduling state is whatever those
 *     ratings actually produced. Writing plausible-looking numbers instead would
 *     put a retention figure on /progress that the schedule contradicts.
 *
 * Credentials come from the environment, not from `.env.example` — that file is
 * the contract for what Vercel needs, and Vercel does not need these:
 *
 *   VITE_SUPABASE_URL, VITE_SUPABASE_PUBLISHABLE_KEY   (read from .env.local)
 *   DEMO_EMAIL, DEMO_PASSWORD                          (the demo account)
 *
 * The account must already exist and be confirmed: sign up through the app once.
 * Imports reach into `src/lib/*.ts` directly, which is why the npm script passes
 * `--experimental-strip-types` (Node 22.13 here; a no-op from Node 22.18 on).
 */
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { createClient } from '@supabase/supabase-js';

import { createSseDecoder } from '../src/lib/sse.ts';
import { StreamEvent, Grade } from '../src/lib/schemas.ts';
import { applyGrade, newCardScheduling, projectCard } from '../src/lib/fsrs.ts';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

// ---------------------------------------------------------------------------
// What the demo account contains
// ---------------------------------------------------------------------------

/** How far back the review log goes. Long enough for a heatmap to have shape. */
const HISTORY_DAYS = 60;

/**
 * Days the demo user did not study, counted back from today. Two clusters early
 * in the window and nothing in the last fortnight: a heatmap with no gaps looks
 * generated, and a gap in the last few days would mean no current streak.
 */
const SKIPPED_DAYS = new Set([57, 56, 41, 33, 32, 31, 22]);

/** Roughly one in six cards is never introduced, so /progress has a `new` slice. */
const UNSEEN_SHARE = 0.17;

/**
 * How the demo user rates. Not uniform — a real log is mostly Good, and the
 * retention split on /progress is only worth showing if Again appears at a
 * believable rate.
 */
const GRADE_WEIGHTS = [
  [Grade.Again, 0.1],
  [Grade.Hard, 0.16],
  [Grade.Good, 0.58],
  [Grade.Easy, 0.16],
];

const DECKS = [
  {
    title: 'Photosynthesis',
    kinds: ['basic', 'cloze'],
    cardCount: 14,
    depth: 'balanced',
    text: `Photosynthesis converts light energy into chemical energy stored in glucose. It runs in two stages. The light-dependent reactions occur in the thylakoid membranes of the chloroplast: chlorophyll in photosystem II absorbs photons, water is split (photolysis) releasing oxygen, electrons pass down an electron transport chain, and the resulting proton gradient across the thylakoid membrane drives ATP synthase. Photosystem I re-energises those electrons to reduce NADP+ to NADPH.

The light-independent reactions, the Calvin cycle, occur in the stroma. RuBisCO fixes carbon dioxide onto ribulose bisphosphate, producing two molecules of 3-phosphoglycerate. ATP and NADPH from the light reactions reduce these to glyceraldehyde 3-phosphate, one molecule of which leaves the cycle per three turns while the rest regenerate RuBP.

RuBisCO also binds oxygen, a wasteful reaction called photorespiration that increases with temperature. C4 plants such as maize concentrate carbon dioxide in bundle sheath cells to suppress it; CAM plants such as cacti open their stomata at night and store carbon as malate until daylight.`,
  },
  {
    title: 'How Postgres indexes work',
    kinds: ['basic', 'mcq'],
    cardCount: 14,
    depth: 'deep',
    text: `A Postgres B-tree index stores keys in sorted order, so the planner can use it for equality, for range scans, and to satisfy an ORDER BY without a sort. An index on (a, b) can serve a predicate on a alone, or on a and b together, but not on b alone: the leading column determines what the index can seek to.

Not every index scan reads the table. An index-only scan is possible when every column the query needs is present in the index and the visibility map says the page is all-visible; otherwise Postgres must visit the heap to check row visibility, because indexes do not store transaction information.

A partial index carries a WHERE clause and indexes only matching rows, which keeps it small when queries always filter the same way. Expression indexes store the result of a function, and only queries using the identical expression can match.

GIN indexes invert composite values, mapping each element to the rows containing it, which is what makes jsonb containment and full-text search fast; they are slower to update than B-trees. Statistics collected by ANALYZE drive the planner's cost estimates, and a stale estimate is the usual reason a perfectly good index is ignored.`,
  },
  {
    title: 'The Roman Republic',
    kinds: ['basic', 'cloze', 'mcq'],
    cardCount: 12,
    depth: 'balanced',
    text: `The Roman Republic was founded traditionally in 509 BC with the expulsion of the last king, Tarquin the Proud. It replaced monarchy with two annually elected consuls who held imperium and could veto one another. The Senate, an unelected body of former magistrates, controlled finance and foreign policy by custom rather than by law.

The Conflict of the Orders was the long struggle by the plebeians for political rights against the patrician aristocracy. It produced the tribunes of the plebs, whose persons were sacrosanct and who could veto magistrates; the Twelve Tables, the first written codification of Roman law, around 450 BC; and eventually the Lex Hortensia of 287 BC, which made plebiscites binding on all citizens.

Expansion followed. The Punic Wars against Carthage between 264 and 146 BC brought Sicily, Spain and North Africa under Roman control, and Hannibal's crossing of the Alps in 218 BC came close to ending the Republic outright. Wealth from conquest concentrated land in fewer hands, and the reforms attempted by the Gracchi brothers ended in political violence. The civil wars of Marius and Sulla, then of Caesar and Pompey, ended the Republic in practice long before Augustus formalised its end in 27 BC.`,
  },
  {
    title: 'Memory and spaced repetition',
    kinds: ['basic', 'cloze'],
    cardCount: 12,
    depth: 'recall',
    text: `Hermann Ebbinghaus, experimenting on himself with nonsense syllables in the 1880s, produced the first forgetting curve: retention falls steeply within hours of learning and then flattens out. He also documented the spacing effect, the finding that repetitions distributed over time produce far more durable memory than the same number massed together.

The testing effect, or retrieval practice, is the finding that trying to recall information strengthens memory more than re-reading it does, even when the attempt fails and is then corrected. Difficulty is part of the mechanism: retrieval that is effortful but successful produces the largest gain, which Bjork called a desirable difficulty.

Modern scheduling algorithms exploit both effects. SM-2, published with SuperMemo in 1987, adjusts an ease factor per card and multiplies the interval by it after each successful recall. FSRS instead models memory with three variables — retrievability, the probability of recall right now; stability, how slowly that probability decays; and difficulty, how much each successful review raises stability — and schedules each card for the day its predicted retrievability crosses a target, by default 0.9.`,
  },
];

// ---------------------------------------------------------------------------
// Environment
// ---------------------------------------------------------------------------

/** Minimal `.env.local` reader: KEY=value, `#` comments, no quoting rules. */
function readEnvFile(path) {
  let raw;
  try {
    raw = readFileSync(path, 'utf8');
  } catch {
    return {};
  }
  const values = {};
  for (const line of raw.split('\n')) {
    const match = /^\s*([A-Z0-9_]+)\s*=\s*(.*)$/.exec(line);
    if (!match) continue;
    values[match[1]] = match[2].trim().replace(/^["']|["']$/g, '');
  }
  return values;
}

function fail(message) {
  console.error(`\n${message}\n`);
  process.exit(1);
}

function loadConfig() {
  const file = readEnvFile(join(root, '.env.local'));
  const read = key => process.env[key] ?? file[key];

  const config = {
    url: read('VITE_SUPABASE_URL'),
    key: read('VITE_SUPABASE_PUBLISHABLE_KEY'),
    email: read('DEMO_EMAIL'),
    password: read('DEMO_PASSWORD'),
  };

  const missing = Object.entries({
    url: 'VITE_SUPABASE_URL',
    key: 'VITE_SUPABASE_PUBLISHABLE_KEY',
    email: 'DEMO_EMAIL',
    password: 'DEMO_PASSWORD',
  })
    .filter(([field]) => !config[field])
    .map(([, name]) => name);
  if (missing.length) {
    fail(
      `Missing configuration: ${missing.join(', ')}.\n` +
        'The Supabase values come from .env.local; DEMO_EMAIL and DEMO_PASSWORD ' +
        'from your shell.',
    );
  }

  // The same refusal src/lib/env-schema.ts makes, for the same reason: this
  // script writes as a signed-in user under RLS, and a secret key would bypass
  // every policy it is supposed to be demonstrating.
  if (config.key.startsWith('sb_secret_')) {
    fail('That is a SECRET key. Use the publishable key (sb_publishable_…).');
  }

  return config;
}

// ---------------------------------------------------------------------------
// Determinism and dates
// ---------------------------------------------------------------------------

/** Seeded PRNG (mulberry32), so two runs produce the same-shaped history. */
function makeRandom(seed) {
  let state = seed >>> 0;
  return () => {
    state = (state + 0x6d2b79f5) >>> 0;
    let t = state;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const random = makeRandom(20260813);

function pickGrade() {
  let roll = random();
  for (const [grade, weight] of GRADE_WEIGHTS) {
    roll -= weight;
    if (roll <= 0) return grade;
  }
  return Grade.Good;
}

const DAY_MS = 86_400_000;

/**
 * How many calendar days ago a moment falls — not how many 24-hour periods.
 *
 * The difference is the whole bug this replaced: measuring elapsed milliseconds
 * puts an evening review one bucket earlier than the evening it happened in
 * whenever the seeder runs before that hour, which quietly dropped reviews onto
 * the days the demo user is supposed to have skipped. /progress buckets by local
 * calendar day (`studyDayKey`), so this does too.
 */
function dayOffsetOf(time) {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const then = new Date(time);
  then.setHours(0, 0, 0, 0);
  return Math.round((today.getTime() - then.getTime()) / DAY_MS);
}

/**
 * A believable moment to have studied on a given day: an evening session, cards
 * a minute or two apart. Local time, because that is the timezone the demo
 * profile carries and the one /progress buckets by.
 */
function studyMoment(dayOffset) {
  const at = new Date(Date.now() - dayOffset * DAY_MS);
  at.setHours(19, 5 + Math.floor(random() * 40), Math.floor(random() * 60), 0);
  return at;
}

// ---------------------------------------------------------------------------
// Generation — the real pipeline, read exactly as useGenerateCards reads it
// ---------------------------------------------------------------------------

function safeJson(text) {
  try {
    return JSON.parse(text);
  } catch {
    return null;
  }
}

async function generateDeck(supabase, config, deck) {
  const { data, error } = await supabase.auth.getSession();
  if (error) throw error;
  const token = data.session?.access_token;
  if (!token) throw new Error('the session went away mid-run');

  const response = await fetch(`${config.url}/functions/v1/generate-cards`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      apikey: config.key,
      'Content-Type': 'application/json',
      Accept: 'text/event-stream',
    },
    body: JSON.stringify({
      text: deck.text,
      cardCount: deck.cardCount,
      kinds: deck.kinds,
      deckTitle: deck.title,
      depth: deck.depth,
    }),
  });

  if (!response.ok || !response.body) {
    const body = await response.text();
    throw new Error(
      `generate-cards answered ${response.status}: ${body.slice(0, 300)}\n` +
        'If that reads like "not configured", the function secrets are not set:\n' +
        '  npx supabase secrets set GROQ_API_KEY=... GENERATION_MODEL=...\n' +
        '  npm run fn:deploy',
    );
  }

  const decoder = new TextDecoder();
  const sse = createSseDecoder();
  const result = { deckId: null, cards: 0, skipped: 0 };
  const startedAt = Date.now();
  let firstCardMs = null;

  for await (const chunk of response.body) {
    for (const frame of sse.push(decoder.decode(chunk, { stream: true }))) {
      const parsed = StreamEvent.safeParse(safeJson(frame.data));
      if (!parsed.success) continue;
      const event = parsed.data;

      if (event.type === 'meta') result.deckId = event.deckId;
      if (event.type === 'card') {
        firstCardMs ??= Date.now() - startedAt;
        result.cards += 1;
      }
      if (event.type === 'warn') result.skipped += 1;
      if (event.type === 'error') throw new Error(`${event.code}: ${event.message}`);
    }
  }

  if (!result.deckId) throw new Error('the stream ended without a meta frame');
  // SPEC §13 (1) — under 5 s to the first card. Printed here because this is the
  // one place the whole pipeline runs unattended against the real provider.
  console.log(
    `    first card in ${firstCardMs ?? 0} ms · ${result.cards} cards · ` +
      `${result.skipped} skipped`,
  );
  return result;
}

/**
 * The review gate, accepted wholesale: `draft` → `active`, then close the deck
 * and stamp the audit row. Mirrors useAcceptDrafts + useFinishReviewGate; the
 * demo is not the place to model a user rejecting cards.
 */
async function acceptDeck(supabase, deckId) {
  const accepted = await supabase
    .from('cards')
    .update({ status: 'active' })
    .eq('deck_id', deckId)
    .eq('status', 'draft')
    .select('id');
  if (accepted.error) throw accepted.error;

  const deck = await supabase.from('decks').update({ status: 'active' }).eq('id', deckId);
  if (deck.error) throw deck.error;

  const stamp = await supabase
    .from('generations')
    .update({ cards_accepted: accepted.data.length })
    .eq('deck_id', deckId);
  if (stamp.error) throw stamp.error;

  return accepted.data.map(row => row.id);
}

// ---------------------------------------------------------------------------
// History — replayed through the scheduler, never invented
// ---------------------------------------------------------------------------

/**
 * Replay one card from its introduction to now.
 *
 * Each rating is applied by `applyGrade` at the moment the card actually came
 * up, and the next review happens when that rating said it should — a day late
 * now and then, because nobody clears their queue every single day. What comes
 * back is the `reviews` rows and the card's final scheduling state, and the two
 * agree by construction rather than by luck.
 */
export function replayCard(userId, cardId, introDay) {
  let scheduling = newCardScheduling(studyMoment(introDay));
  let at = new Date(scheduling.due);
  const rows = [];

  // A card cannot outlive its own history; the cap only stops a pathological
  // learning-step loop from running forever.
  for (let step = 0; step < 60; step += 1) {
    const result = applyGrade(scheduling, pickGrade(), at, {
      durationMs: 2500 + Math.floor(random() * 9000),
    });
    const log = result.log;

    rows.push({
      user_id: userId,
      card_id: cardId,
      rating: log.rating,
      reviewed_at: log.reviewed_at,
      duration_ms: log.duration_ms,
      state_before: log.state_before,
      stability_before: log.stability_before,
      difficulty_before: log.difficulty_before,
      due_before: log.due_before,
      last_review_before: log.last_review_before,
      // The card's own stale counter, which is what undo has to put back — not
      // the same number as `elapsed_days`, which is what actually elapsed.
      elapsed_days_before: scheduling.elapsed_days,
      learning_steps_before: log.learning_steps_before,
      elapsed_days: log.elapsed_days,
      scheduled_days: log.scheduled_days,
      state_after: log.state_after,
      stability_after: log.stability_after,
      difficulty_after: log.difficulty_after,
    });

    scheduling = projectCard(scheduling, result);

    const due = new Date(scheduling.due).getTime();
    if (due > Date.now()) break;

    // A learning card comes back within the same sitting; one due on a later day
    // waits for that evening's session, and sometimes the one after it.
    const dueDay = dayOffsetOf(due);
    let next =
      dueDay === dayOffsetOf(at.getTime())
        ? new Date(due + (3 + random() * 25) * 60_000)
        : studyMoment(Math.max(0, dueDay - (random() < 0.25 ? 1 : 0)));

    // Days the user did not study are days on which nothing was rated: the card
    // waits, it does not get answered early.
    while (SKIPPED_DAYS.has(dayOffsetOf(next.getTime()))) {
      next = new Date(next.getTime() + DAY_MS);
    }

    // Session times are drawn at random within the evening, so the next draw can
    // land before the last one. A review log that goes backwards is not a log.
    if (next.getTime() <= at.getTime()) {
      next = new Date(at.getTime() + (3 + random() * 25) * 60_000);
    }

    if (next.getTime() > Date.now()) break;
    at = next;
  }

  return { rows, scheduling };
}

async function seedHistory(supabase, userId, cardIds) {
  // The days the demo user studied, oldest first. Introductions are spread
  // across all of them, so every one has at least one review on it and the
  // streak runs unbroken to today.
  const introDays = [];
  for (let day = HISTORY_DAYS; day >= 1; day -= 1) {
    if (!SKIPPED_DAYS.has(day)) introDays.push(day);
  }

  // Which cards were ever seen is decided first, so the ones that were can be
  // spread across the *whole* window. Deciding as we go would bunch the
  // introductions into the oldest days and leave the recent end — the part a
  // visitor actually looks at — with nothing on it.
  const seen = cardIds.filter(() => random() >= UNSEEN_SHARE);
  const reviews = [];

  for (const [index, cardId] of seen.entries()) {
    const introDay = introDays[Math.floor((index * introDays.length) / seen.length)];
    const { rows, scheduling } = replayCard(userId, cardId, introDay);
    reviews.push(...rows);

    const update = await supabase
      .from('cards')
      .update({
        fsrs_state: scheduling.fsrs_state,
        stability: scheduling.stability,
        difficulty: scheduling.difficulty,
        due: scheduling.due,
        last_review: scheduling.last_review,
        reps: scheduling.reps,
        lapses: scheduling.lapses,
        scheduled_days: scheduling.scheduled_days,
        elapsed_days: scheduling.elapsed_days,
        learning_steps: scheduling.learning_steps,
      })
      .eq('id', cardId);
    if (update.error) throw update.error;
  }

  for (let start = 0; start < reviews.length; start += 400) {
    const { error } = await supabase
      .from('reviews')
      .insert(reviews.slice(start, start + 400));
    if (error) throw error;
  }

  return { introduced: seen.length, reviews: reviews.length };
}

// ---------------------------------------------------------------------------
// Reset
// ---------------------------------------------------------------------------

/**
 * Deletes every deck on the demo account, which cascades to its cards and their
 * reviews. Destructive, and deliberately behind a flag: CLAUDE.md treats
 * deleting rows in the live project as something to ask about first, and a
 * seeder that wipes whatever account it is pointed at by default is that mistake
 * waiting for a mistyped DEMO_EMAIL.
 */
async function resetAccount(supabase, userId) {
  const decks = await supabase.from('decks').select('id, title').eq('user_id', userId);
  if (decks.error) throw decks.error;
  if (!decks.data.length) return;

  console.log(`  deleting ${decks.data.length} decks, with their cards and reviews:`);
  for (const deck of decks.data) console.log(`    - ${deck.title}`);

  const { error } = await supabase.from('decks').delete().eq('user_id', userId);
  if (error) throw error;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  const config = loadConfig();
  const reset = process.argv.includes('--reset');

  const supabase = createClient(config.url, config.key, {
    auth: { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false },
  });

  const signIn = await supabase.auth.signInWithPassword({
    email: config.email,
    password: config.password,
  });
  if (signIn.error) {
    fail(
      `Could not sign in as ${config.email}: ${signIn.error.message}\n` +
        'The demo account must already exist and be confirmed — sign up through the ' +
        'app once, follow the confirmation link, then run this again.',
    );
  }
  const userId = signIn.data.user.id;
  console.log(`signed in as ${config.email} (${userId})`);

  const existing = await supabase
    .from('decks')
    .select('id', { count: 'exact', head: true })
    .eq('user_id', userId);
  if (existing.error) fail(existing.error.message);

  if (existing.count && !reset) {
    fail(
      `This account already has ${existing.count} decks. Re-run with --reset to ` +
        'delete them and rebuild, or point DEMO_EMAIL at a different account.',
    );
  }
  if (reset) await resetAccount(supabase, userId);

  const cardIds = [];
  for (const [index, deck] of DECKS.entries()) {
    // SPEC §7.5 control 4 allows three generations per 60 seconds. They take long
    // enough that this rarely bites, but the fourth deck is exactly where it would,
    // and a 429 half way through a seed leaves a mess to clean up.
    if (index > 0 && index % 3 === 0) {
      console.log('\npausing 60s for the burst limiter…');
      await new Promise(resolve => setTimeout(resolve, 61_000));
    }

    console.log(`\n[${index + 1}/${DECKS.length}] generating "${deck.title}"…`);
    const generated = await generateDeck(supabase, config, deck);
    const accepted = await acceptDeck(supabase, generated.deckId);
    console.log(`    accepted ${accepted.length} cards`);
    cardIds.push(...accepted);
  }

  console.log(
    `\nreplaying ${HISTORY_DAYS} days of reviews over ${cardIds.length} cards…`,
  );
  const history = await seedHistory(supabase, userId, cardIds);
  console.log(
    `  ${history.reviews} reviews across ${history.introduced} cards; ` +
      `${cardIds.length - history.introduced} left unseen`,
  );

  console.log('\nDone. Sign in as the demo account and check /progress.');
  await supabase.auth.signOut();
}

// Importable without running, so the replay can be exercised offline.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  await main();
}
